version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node
        environment:
          - RAILS_ENV=test
          - RACK_ENV=test
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install gems
          command: bundle install --path ~/.cache/bundle
      - save_cache:
          key: bundle-{{.Branch}}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.cache/bundle
      - run:
          name: Run tests
          command: bundle exec rspec
      - run:
          name: Check code style
          command: bundle exec rubocop
  deploy:
    docker:
      - image: circleci/ruby:2.7.1-node
    steps:
      - checkout
      - run:
          name: Tag the version
          command: |
            version=$(cat lib/cirro-ruby-client/version.rb | grep VERSION | awk -F' = ' '{print $2}' | xargs)
            git tag v"$version"
            git push origin v"$version"
      - run:
          name: build gem
          command: gem build cirro-ruby-client.gemspec
      - run:
          name: push to rubygems
          command: |
            echo "gem `gem --version`"
            mkdir ~/.gem
            cat .circleci/gem_credentials | sed -e "s/__RUBYGEMS_API_KEY__/${RUBYGEMS_API_KEY}/" > ~/.gem/credentials
            chmod 0600 ~/.gem/credentials
            gem push my_gem-*.gem
            shred -u ~/.gem/credentials

workflows:
  version: 2
  deploy_the_gem:
    jobs:
      - build
      - deploy:
          requires:
            - build
